version: "3"
networks:
  mao:
volumes:
  db_data:
  shared_data:
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - mao
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        ENV: ${ENV}
    env_file:
      - .env
    networks:
      - mao
    depends_on:
      - db
    ports:
      - 4000:4000
    entrypoint: /app/entrypoint.sh
    command: ["bin/mao", "start"]
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        API_URL: ${API_URL}
        SOCKET_URL: ${SOCKET_URL}
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - mao
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${SERVER_PORT}:80
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - mao
    depends_on:
      - frontend
      - backend
